[mos_ru]
host = pochta.mos.ru
port = 993
use_ssl = true

login = HQ\MedvedevSS
password = aoMMM2026!!!

# Куда слать уведомления по этому ящику (можно пустым, если общий admin_chat_id в config.ini)
telegram_chat_id =272250747

# Опционально (можно пустыми)
username =
name =

[telegram]
bot_token = 8280024825:AAEjGrUWYenStG3zRR2rrhzqnSxvKZ1Mo6Y

[cloudflare]
account_id = 
api_token = 

[gigachat]
api_key = fe3d-7b1f-9de9-3cd44ceda3e5

[llm]
primary = gigachat
fallback = cloudflare


[letterbot_ru]
host = imap.ya.ru
port = 993
use_ssl = true

login = master@letterbot.ru
password = tarzexwmpdrafful

telegram_chat_id =272250747