import re
from typing import List, Set, Tuple


STOPWORDS: Set[str] = {
    "and",
    "the",
    "for",
    "with",
    "this",
    "that",
    "from",
    "into",
    "about",
    "your",
    "yours",
    "our",
    "ours",
    "their",
    "theirs",
    "without",
    "within",
    "between",
    "upon",
    "have",
    "has",
    "had",
    "will",
    "shall",
    "would",
    "could",
    "should",
    "been",
    "being",
    "because",
    "which",
    "while",
    "when",
    "then",
    "than",
    "also",
    "such",
    "very",
    "here",
    "there",
    "once",
    "some",
    "any",
    "each",
    "other",
    "only",
    "does",
    "is",
    "are",
    "was",
    "were",
    "not",
    "ain't",
    "cant",
    "can't",
    "cannot",
    "don't",
    "dont",
    "didn't",
    "didnt",
    "won't",
    "wont",
    "i",
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "them",
    "his",
    "her",
    "its",
    "their",
    "mine",
    "yours",
    "ours",
    "theirs",
    "and",
    "but",
    "or",
    "nor",
    "to",
    "too",
    "very",
    "much",
    "more",
    "most",
    "many",
    "few",
    "lot",
    "lots",
    "of",
    "in",
    "on",
    "at",
    "by",
    "an",
    "a",
    "no",
    "yes",
    "so",
    "as",
    "if",
    "up",
    "out",
    "over",
    "after",
    "before",
    "under",
    "again",
    "further",
    # Russian stopwords (minimal set)
    "и",
    "в",
    "во",
    "на",
    "но",
    "а",
    "что",
    "это",
    "как",
    "к",
    "из",
    "по",
    "за",
    "не",
    "ни",
    "да",
    "нет",
    "мы",
    "вы",
    "он",
    "она",
    "они",
    "их",
    "его",
    "ее",
    "её",
    "у",
    "о",
    "об",
    "для",
    "с",
    "со",
    "же",
    "ли",
    "или",
    "то",
    "так",
    "также",
    "бы",
    "быть",
    "когда",
}


def extract_content_words(text: str) -> Set[str]:
    words = re.findall(r"[A-Za-zА-Яа-яЁё0-9']+", text.lower())
    return {word for word in words if len(word) >= 4 and word not in STOPWORDS}


def validate_overlap(summary: str, original: str) -> Tuple[bool, float]:
    summary_words = extract_content_words(summary)
    original_words = extract_content_words(original)
    overlap = len(summary_words & original_words)
    ratio = overlap / max(1, len(summary_words))
    threshold = 0.20 if len(summary_words) < 12 else 0.30
    return ratio >= threshold, ratio


def detect_templates(text: str) -> List[str]:
    patterns = [
        r"касается .*? темы",
        r"без подробност",
        r"можно .*? просмотр",
        r"документ .*? по теме",
        r"файл .*? дополняет",
    ]
    matches: List[str] = []
    for pattern in patterns:
        if re.search(pattern, text, flags=re.IGNORECASE | re.DOTALL):
            matches.append(pattern)
    return matches
